version: 2.1
jobs:
  build:
    working_directory: ~/oddvest
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          key: oddvest-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: oddvest-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Lint and type-check files
          command: yarn lint
      - run:
          name: Run unit tests
          command: yarn test:ci
      - run:
          name: Report Test Coverage
          command: yarn test:coverage
      - store_artifacts:
          path: coverage
          destination: js-reports
      - store_test_results:
          path: coverage
