version: 2.1
jobs:
  build:
    working_directory: ~/oddvest
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - restore_cache:
          key: oddvest-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}-{{ checksum ".yarnrc" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: oddvest-{{ checksum ".nvmrc" }}-{{ checksum "yarn.lock" }}-{{ checksum ".yarnrc" }}
          paths:
            - ./node_modules
      - run:
          name: Lint and type-check files
          command: yarn lint
      - run:
          name: Run unit tests
          command: yarn jest --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: './coverage'
      - run:
          name: Report Test Coverage
          command: yarn test:coverage
      - store_artifacts:
          path: coverage
          destination: js-test-reports
      - store_test_results:
          path: coverage
